spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://github.com/devPracticeCenter/eks-apps.git"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true