apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sample-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-sample-ingress
  annotations:
    nginx.ingress.kubernetes.io/client-body-timeout: "7200"
    nginx.ingress.kubernetes.io/client-header-timeout: "7200"
    nginx.ingress.kubernetes.io/client-max-body-size: 5000m
    nginx.ingress.kubernetes.io/keep-alive: "300"
    nginx.ingress.kubernetes.io/keepalive-timeout: "300"
    nginx.ingress.kubernetes.io/large-client-header-buffers: 64 128k
    nginx.ingress.kubernetes.io/proxy-body-size: 5000m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/send_timeout: "7200"
    nginx.ingress.kubernetes.io/server-snippet: |
      grpc_read_timeout 120s;
      grpc_send_timeout 120s;
      client_body_timeout 120s;
spec:
  ingressClassName: "nginx"
  rules:
  - host: project-03.geunsam2.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-sample-service
            port:
              number: 80
