apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack # var
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: addons/prometheus-stack # var
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Replace=true
    - CreateNamespace=true