apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-class
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/devPracticeCenter/eks-apps.git"
    targetRevision: main
    path: _apps/class
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
